# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12I8jH7iVXUJf-Gq4fefR8_yCYmdk_6B_
"""

import React, { useState } from 'react';

export default function App() {
  const [currentTicket, setCurrentTicket] = useState('A102');
  const [selectedService, setSelectedService] = useState('Nộp tiền');
  const [waitingCount, setWaitingCount] = useState(6);
  const [notification, setNotification] = useState(null);

  const generateTicket = (service) => {
    const prefix = service === 'Mở tài khoản' || service === 'Vay vốn' ? 'B' : 'A';
    const randomNumber = Math.floor(100 + Math.random() * 900);
    const newTicket = `${prefix}${randomNumber}`;

    setSelectedService(service);
    setCurrentTicket(newTicket);
    setWaitingCount(Math.floor(Math.random() * 10) + 1);

    // Replaced alert() with a custom UI notification
    setNotification(`Đã lấy số thành công: ${newTicket}`);
    setTimeout(() => {
      setNotification(null);
    }, 3000); // Auto-hide after 3 seconds
  };

  const waitingList = [
    { number: 'A102', service: 'Nộp tiền' },
    { number: 'A103', service: 'Rút tiền' },
    { number: 'B021', service: 'Mở tài khoản' },
  ];

  const counters = [
    { id: 1, current: 'A101' },
    { id: 2, current: 'B020' },
    { id: 3, current: 'A099' },
  ];

  const services = [
    'Nộp tiền',
    'Rút tiền',
    'Mở tài khoản',
    'Vay vốn',
    'Internet Banking',
    'CSKH',
  ];

  return (
    <div className="min-h-screen bg-[#f4f7fb] text-gray-900 relative">

      {/* TOAST NOTIFICATION */}
      {notification && (
        <div className="fixed top-6 right-6 bg-green-500 text-white px-6 py-4 rounded-2xl shadow-2xl z-50 flex items-center gap-3 animate-bounce">
          <div className="w-6 h-6 bg-white rounded-full flex items-center justify-center text-green-500 font-bold">
            ✓
          </div>
          <span className="font-semibold">{notification}</span>
        </div>
      )}

      {/* HEADER */}
      <header className="bg-[#005BAC] shadow-lg border-b-4 border-red-600 sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="w-14 h-14 rounded-full bg-white flex items-center justify-center shadow-md">
              <div className="w-8 h-8 rounded-full border-[6px] border-[#005BAC] border-r-red-600 rotate-45" />
            </div>

            <div>
              <h1 className="text-xl md:text-2xl font-bold text-white tracking-wide">
                VIETINBANK SMART QUEUE
              </h1>
              <p className="text-blue-100 text-xs md:text-sm">
                Hệ thống lấy số giao dịch tự động
              </p>
            </div>
          </div>

          <div className="hidden md:flex items-center gap-3">
            <div className="bg-white/15 px-4 py-2 rounded-xl text-white text-sm backdrop-blur-sm">
              Chi nhánh: Bình Dương
            </div>

            <div className="bg-red-600 px-4 py-2 rounded-xl text-white font-semibold shadow-lg flex items-center gap-2">
              <span className="w-2 h-2 bg-white rounded-full animate-pulse"></span>
              LIVE
            </div>
          </div>
        </div>
      </header>

      {/* HERO */}
      <section className="relative overflow-hidden bg-gradient-to-r from-[#005BAC] to-[#0b75d1] text-white">
        <div className="absolute inset-0 opacity-10 pointer-events-none">
          <div className="absolute top-0 left-0 w-96 h-96 bg-white rounded-full blur-3xl" />
          <div className="absolute bottom-0 right-0 w-96 h-96 bg-red-500 rounded-full blur-3xl" />
        </div>

        <div className="relative max-w-7xl mx-auto px-6 py-14 grid lg:grid-cols-2 gap-10 items-center">
          <div>
            <h2 className="text-4xl md:text-5xl font-black leading-tight mb-6">
              Lấy số giao dịch
              <br />
              bằng QR Code
            </h2>

            <p className="text-blue-100 text-lg leading-relaxed max-w-xl">
              Khách hàng chỉ cần quét mã QR để lấy số tự động, theo dõi hàng chờ realtime và được gọi trực tiếp tới quầy giao dịch.
            </p>

            <div className="mt-8 flex flex-wrap gap-4">
              <button
                onClick={() => document.getElementById('services-section')?.scrollIntoView({ behavior: 'smooth' })}
                className="bg-white text-[#005BAC] font-bold px-6 py-3 rounded-2xl shadow-xl hover:scale-105 transition active:scale-95"
              >
                Quét QR để lấy số
              </button>

              <button
                onClick={() => document.getElementById('live-queue')?.scrollIntoView({ behavior: 'smooth' })}
                className="bg-red-600 text-white font-bold px-6 py-3 rounded-2xl shadow-xl hover:scale-105 transition active:scale-95">
                Theo dõi hàng chờ
              </button>
            </div>
          </div>

          {/* QR CARD */}
          <div className="flex justify-center">
            <div className="bg-white rounded-3xl p-8 shadow-2xl w-full max-w-md relative">
              <div className="text-center mb-6">
                <h3 className="text-2xl font-black text-[#005BAC]">
                  QUÉT MÃ QR
                </h3>
                <p className="text-gray-500 mt-2">
                  Để lấy số giao dịch tự động
                </p>
              </div>

              <div className="bg-gray-100 rounded-3xl p-6 flex items-center justify-center">
                <button
                  onClick={() => document.getElementById('services-section')?.scrollIntoView({ behavior: 'smooth' })}
                  className="w-64 h-64 bg-white border-[16px] border-[#005BAC] rounded-2xl grid grid-cols-6 gap-1 p-2 cursor-pointer hover:scale-105 transition shadow-inner focus:outline-none"
                  aria-label="Quét mã QR"
                >
                  {Array.from({ length: 36 }).map((_, i) => (
                    <div
                      key={i}
                      className={`rounded-sm ${
                        Math.random() > 0.5 ? 'bg-black' : 'bg-white'
                      }`}
                    />
                  ))}
                </button>
              </div>

              <div className="mt-4 text-center text-sm text-gray-500 font-medium">
                Nhấn vào QR để lấy số giao dịch
              </div>

              <div className="mt-6 bg-[#005BAC] rounded-2xl p-5 text-white text-center shadow-lg">
                <div className="text-sm text-blue-100">Số hiện tại của bạn</div>
                <div className="text-6xl font-black mt-2 tracking-wider">{currentTicket}</div>
                <div className="mt-3 text-blue-100 font-medium">
                  Dịch vụ: {selectedService}
                </div>

                <div className="mt-2 text-blue-100">
                  Đang chờ: <span className="font-bold text-white">{waitingCount}</span> khách
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* SERVICES */}
      <section id="services-section" className="max-w-7xl mx-auto px-6 py-14">
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4">
          <div>
            <h3 className="text-3xl font-black text-[#005BAC]">
              Chọn dịch vụ giao dịch
            </h3>
            <p className="text-gray-500 mt-2">
              Chạm để lấy số tự động
            </p>
          </div>

          <div className="hidden lg:inline-block bg-red-600 text-white px-5 py-3 rounded-2xl font-semibold shadow-lg">
            VietinBank Digital Branch
          </div>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {services.map((service) => (
            <button
              key={service}
              onClick={() => generateTicket(service)}
              className="group bg-white rounded-3xl p-8 shadow-md hover:shadow-2xl hover:-translate-y-2 transition border border-gray-100 text-left focus:outline-none focus:ring-4 focus:ring-blue-100"
            >
              <div className="w-16 h-16 rounded-2xl bg-[#005BAC]/10 flex items-center justify-center mb-6 group-hover:bg-red-600 transition">
                <div className="w-8 h-8 rounded-lg bg-[#005BAC] group-hover:bg-white transition" />
              </div>

              <h4 className="text-2xl font-black text-[#005BAC] group-hover:text-red-600 transition">
                {service}
              </h4>

              <p className="text-gray-500 mt-3 leading-relaxed">
                Lấy số giao dịch nhanh chóng và theo dõi realtime ngay trên điện thoại.
              </p>

              <div className="mt-6 flex items-center justify-between">
                <span className="text-sm text-gray-400 font-medium">Thời gian chờ ~5 phút</span>

                <div className="bg-[#005BAC] text-white px-4 py-2 rounded-xl font-semibold group-hover:bg-red-600 transition">
                  Lấy số
                </div>
              </div>
            </button>
          ))}
        </div>
      </section>

      {/* LIVE QUEUE */}
      <section id="live-queue" className="bg-white py-14 border-y border-gray-200">
        <div className="max-w-7xl mx-auto px-6 grid lg:grid-cols-2 gap-10">
          {/* WAITING LIST */}
          <div className="bg-[#f8fbff] rounded-3xl p-6 md:p-8 shadow-lg border border-blue-100">
            <div className="flex items-center justify-between mb-8">
              <div>
                <h3 className="text-2xl md:text-3xl font-black text-[#005BAC]">
                  Hàng chờ realtime
                </h3>
                <p className="text-gray-500 mt-2">
                  Danh sách khách đang chờ giao dịch
                </p>
              </div>

              <div className="bg-green-100 text-green-700 px-4 py-2 rounded-xl font-semibold flex items-center gap-2">
                <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
                Online
              </div>
            </div>

            <div className="space-y-4">
              {waitingList.map((ticket) => (
                <div
                  key={ticket.number}
                  className="bg-white rounded-2xl p-5 shadow-sm flex items-center justify-between border border-gray-100 hover:shadow-md transition"
                >
                  <div>
                    <div className="text-3xl font-black text-[#005BAC]">
                      {ticket.number}
                    </div>
                    <div className="text-gray-500 mt-1 font-medium">
                      {ticket.service}
                    </div>
                  </div>

                  <div className="bg-yellow-100 text-yellow-700 px-4 py-2 rounded-xl font-semibold">
                    Đang chờ
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* COUNTERS */}
          <div className="bg-[#005BAC] rounded-3xl p-6 md:p-8 shadow-2xl text-white relative overflow-hidden">
            <div className="absolute top-0 right-0 w-72 h-72 bg-red-600 rounded-full blur-3xl opacity-20 pointer-events-none" />

            <div className="relative">
              <h3 className="text-2xl md:text-3xl font-black mb-2">
                Quầy đang phục vụ
              </h3>

              <p className="text-blue-100 mb-8">
                Cập nhật realtime từ giao dịch viên
              </p>

              <div className="space-y-5">
                {counters.map((counter) => (
                  <div
                    key={counter.id}
                    className="bg-white/10 backdrop-blur rounded-2xl p-6 border border-white/10 hover:bg-white/20 transition"
                  >
                    <div className="flex items-center justify-between">
                      <div>
                        <div className="text-blue-100 text-sm font-medium uppercase tracking-wider">
                          Quầy giao dịch
                        </div>
                        <div className="text-2xl md:text-3xl font-black mt-1">
                          QUẦY {counter.id < 10 ? `0${counter.id}` : counter.id}
                        </div>
                      </div>

                      <div className="text-right">
                        <div className="text-blue-100 text-sm font-medium uppercase tracking-wider">
                          Đang gọi số
                        </div>
                        <div className="text-4xl md:text-5xl font-black text-yellow-300 mt-1 animate-pulse">
                          {counter.current}
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* STAFF DASHBOARD */}
      <section className="max-w-7xl mx-auto px-6 py-16">
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-10 gap-4">
          <div>
            <h3 className="text-3xl md:text-4xl font-black text-[#005BAC]">
              Dashboard giao dịch viên
            </h3>
            <p className="text-gray-500 mt-2">
              Điều khiển realtime cho từng quầy
            </p>
          </div>

          <div className="hidden lg:inline-block bg-[#005BAC] text-white px-5 py-3 rounded-2xl shadow-lg font-semibold">
            Teller Panel
          </div>
        </div>

        <div className="bg-white rounded-[32px] shadow-2xl overflow-hidden border border-gray-100">
          <div className="bg-gradient-to-r from-[#005BAC] to-[#0a6cc1] text-white px-6 md:px-8 py-6 flex items-center justify-between">
            <div>
              <div className="text-sm text-blue-100 uppercase tracking-wider font-medium">Đăng nhập</div>
              <div className="text-2xl md:text-3xl font-black mt-1">QUẦY 03</div>
            </div>

            <div className="bg-red-600 px-5 py-3 rounded-2xl font-bold shadow-lg text-sm md:text-base">
              ĐANG PHỤC VỤ
            </div>
          </div>

          <div className="p-6 md:p-10">
            <div className="grid lg:grid-cols-2 gap-10">
              <div className="bg-[#f8fbff] rounded-3xl p-8 border border-blue-100 flex flex-col justify-center items-center text-center">
                <div className="text-gray-500 text-lg font-medium">
                  Số hiện tại đang phục vụ
                </div>

                <div className="text-[100px] md:text-[120px] leading-none font-black text-[#005BAC] mt-4 tracking-tighter">
                  A101
                </div>

                <div className="mt-6 inline-block bg-blue-100 text-[#005BAC] px-6 py-2 rounded-full font-bold">
                  Khách hàng: Nộp tiền
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4 md:gap-5">
                <button className="bg-[#005BAC] text-white rounded-3xl p-4 md:p-6 text-lg md:text-xl font-black shadow-lg hover:shadow-xl hover:scale-105 active:scale-95 transition flex flex-col items-center justify-center gap-2">
                  <span className="text-3xl">⏭️</span>
                  Gọi tiếp
                </button>

                <button className="bg-red-600 text-white rounded-3xl p-4 md:p-6 text-lg md:text-xl font-black shadow-lg hover:shadow-xl hover:scale-105 active:scale-95 transition flex flex-col items-center justify-center gap-2">
                  <span className="text-3xl">📢</span>
                  Gọi lại
                </button>

                <button className="bg-yellow-500 text-white rounded-3xl p-4 md:p-6 text-lg md:text-xl font-black shadow-lg hover:shadow-xl hover:scale-105 active:scale-95 transition flex flex-col items-center justify-center gap-2">
                  <span className="text-3xl">🚫</span>
                  Bỏ qua
                </button>

                <button className="bg-green-600 text-white rounded-3xl p-4 md:p-6 text-lg md:text-xl font-black shadow-lg hover:shadow-xl hover:scale-105 active:scale-95 transition flex flex-col items-center justify-center gap-2">
                  <span className="text-3xl">✅</span>
                  Hoàn tất
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="bg-[#003d73] text-white py-10 mt-10">
        <div className="max-w-7xl mx-auto px-6 flex flex-col lg:flex-row items-center justify-between gap-6 text-center lg:text-left">
          <div>
            <div className="text-2xl font-black tracking-wide">
              VIETINBANK SMART QUEUE
            </div>

            <div className="text-blue-200 mt-2 font-medium">
              Hệ thống giao dịch số hóa realtime bằng QR Code
            </div>
          </div>

          <div className="flex flex-wrap justify-center gap-3 md:gap-4">
            <div className="bg-white/10 px-5 py-3 rounded-2xl text-sm font-medium">
              Realtime Queue
            </div>
            <div className="bg-white/10 px-5 py-3 rounded-2xl text-sm font-medium">
              QR Check-in
            </div>
            <div className="bg-white/10 px-5 py-3 rounded-2xl text-sm font-medium">
              Socket.IO Live
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}