# -*- coding: utf-8 -*-
"""VietinBank Smart Queue

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdYb_9VsY7TsW1sQ2npA15piio2jN7oH
"""

import streamlit as st
import random
import time

# --- CẤU HÌNH TRANG ---
st.set_page_config(
    page_title="VietinBank Smart Queue",
    page_icon="🏦",
    layout="wide"
)

# --- CSS TÙY CHỈNH (Giả lập màu sắc VietinBank) ---
st.markdown("""
<style>
    .main-title { color: #005BAC; font-weight: 900; font-size: 40px; }
    .ticket-number { color: #005BAC; font-weight: 900; font-size: 80px; text-align: center; }
    .counter-text { color: #D32F2F; font-weight: bold; font-size: 30px; }
</style>
""", unsafe_allow_html=True)

# --- KHỞI TẠO TRẠNG THÁI (STATE) ---
if 'current_ticket' not in st.session_state:
    st.session_state.current_ticket = 'A102'
if 'selected_service' not in st.session_state:
    st.session_state.selected_service = 'Nộp tiền'
if 'waiting_count' not in st.session_state:
    st.session_state.waiting_count = 6
if 'waiting_list' not in st.session_state:
    st.session_state.waiting_list = [
        {'number': 'A102', 'service': 'Nộp tiền'},
        {'number': 'A103', 'service': 'Rút tiền'},
        {'number': 'B021', 'service': 'Mở tài khoản'},
    ]

# --- HÀM XỬ LÝ LẤY SỐ ---
def generate_ticket(service):
    prefix = 'B' if service in ['Mở tài khoản', 'Vay vốn'] else 'A'
    new_ticket = f"{prefix}{random.randint(100, 999)}"

    st.session_state.selected_service = service
    st.session_state.current_ticket = new_ticket
    st.session_state.waiting_count = random.randint(1, 10)

    # Thêm vào danh sách chờ
    st.session_state.waiting_list.insert(0, {
        'number': new_ticket,
        'service': service
    })

    # Hiển thị thông báo (Toast)
    st.toast(f"Đã lấy số thành công: {new_ticket}", icon="✅")

# --- GIAO DIỆN CHÍNH ---
st.markdown("<div class='main-title'>🏦 VIETINBANK SMART QUEUE</div>", unsafe_allow_html=True)
st.caption("Hệ thống lấy số giao dịch tự động bằng Python & Streamlit")
st.divider()

# Khu vực Lấy số và Hiển thị thẻ
col_services, col_ticket = st.columns([1.5, 1])

with col_services:
    st.markdown("### 👉 Chọn dịch vụ giao dịch")
    services = ['Nộp tiền', 'Rút tiền', 'Mở tài khoản', 'Vay vốn', 'Internet Banking', 'CSKH']

    # Tạo grid nút bấm
    cols = st.columns(2)
    for i, service in enumerate(services):
        if cols[i%2].button(f"{service}", use_container_width=True, key=f"btn_{i}"):
            generate_ticket(service)

with col_ticket:
    st.markdown("### 🎫 Số hiện tại của bạn")
    with st.container(border=True):
        st.info(f"**Dịch vụ:** {st.session_state.selected_service}")
        st.markdown(f"<div class='ticket-number'>{st.session_state.current_ticket}</div>", unsafe_allow_html=True)
        st.warning(f"⏳ Đang chờ: **{st.session_state.waiting_count}** khách")

st.divider()

# Khu vực Hàng chờ và Quầy phục vụ
col_queue, col_counter = st.columns([1, 1])

with col_queue:
    st.markdown("### 📋 Hàng chờ realtime")
    # Hiển thị 5 khách gần nhất
    for ticket in st.session_state.waiting_list[:5]:
        st.success(f"**{ticket['number']}** - Dịch vụ: {ticket['service']}")

with col_counter:
    st.markdown("### 🖥️ Quầy đang phục vụ")
    counters = [
        {'id': 1, 'current': 'A101'},
        {'id': 2, 'current': 'B020'},
        {'id': 3, 'current': 'A099'},
    ]

    for c in counters:
        with st.container(border=True):
            st.markdown(f"QUẦY 0{c['id']} ➡️ Đang gọi: <span class='counter-text'>{c['current']}</span>", unsafe_allow_html=True)

# Footer
st.markdown("<br><hr><center><i>Phát triển trên nền tảng Python Streamlit</i></center>", unsafe_allow_html=True)